apiVersion: batch/v1
kind: Job
metadata:
  name: jhof-train-gpu
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/arch: amd64
        # Co-locate with the rook-ceph-block-fullerton pool; reading the 8 GB CSV
        # from another region drops throughput to very little
        topology.kubernetes.io/zone: ucsd
      containers:
        - name: train-gpu
          image: ghcr.io/jannikh00/higgs-k8s-gpu-benchmark:cdfca6a9c70464c39d4589aa78e74dc9bcfcc26d
          command:
            - python3
            - src/train.py
            - --device
            - cuda
            - --threads
            - "8"
            - --batch-size
            - "1024"
            - --data-path
            - /data/HIGGS.csv
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: "8"
              memory: 16Gi
              nvidia.com/gpu: 1
            limits:
              cpu: "8"
              memory: 16Gi
              nvidia.com/gpu: 1
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jhof-higgs-data
